<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubCategory extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::query(
            "INSERT INTO `nominal`.`sub_categories` (`id`, `sub_category`, `category_id`, `sub_category_slug`, `created_at`, `updated_at`) VALUES (1, 'Cars', 1, 'cars', NULL, NULL),
            (2, 'Suvs', 1, 'suvs', NULL, NULL),
            (3, 'For Sale: Houses & Apartments', 2, 'for-sale-houses-apartments', NULL, NULL),
            (4, 'For Rent: Houses & Apartments', 2, 'for-rent-house-apartments', NULL, NULL),
            (5, 'Lands & Plots', 2, 'lands-plots', NULL, NULL),
            (6, 'For Rent: Shops & Offices', 2, 'for-rent-shops-offices', NULL, NULL),
            (7, 'For Sale: Shops & Offices', 2, 'for-sale-shops-offices', NULL, NULL),
            (8, 'PG', 2, 'paying-guest-pg', NULL, NULL),
            (9, 'Guest Houses', 2, 'guest-houses', NULL, NULL),
            (10, 'Mobile Phones', 3, 'mobile-phones', NULL, NULL),
            (11, 'Mobile Accessories', 3, 'mobile-accessories', NULL, NULL),
            (12, 'Tablets', 3, 'tablets', NULL, NULL),
            (13, 'Iphone', 3, 'iphone', NULL, NULL),
            (14, 'Samsung', 3, 'samsung', NULL, NULL),
            (15, 'Realme', 3, 'realme', NULL, NULL),
            (16, 'Oppo', 3, 'oppo', NULL, NULL),
            (17, 'Vivo', 3, 'vivo', NULL, NULL),
            (18, 'Xiaomi', 3, 'mi', NULL, NULL),
            (19, 'Micromax', 3, 'micromax', NULL, NULL),
            (20, 'Htc', 3, 'htc', NULL, NULL),
            (21, 'Lenovo', 3, 'lenovo', NULL, NULL),
            (22, 'Oneplus', 3, 'oneplus', NULL, NULL),
            (23, 'Huawei', 3, 'huawei', NULL, NULL),
            (24, 'Infinix', 3, 'infinix', NULL, NULL),
            (25, 'Intex', 3, 'intex', NULL, NULL),
            (26, 'Karbon', 3, 'karbon', NULL, NULL),
            (27, 'Lava', 3, 'lava', NULL, NULL),
            (28, 'LG', 3, 'lg', NULL, NULL),
            (29, 'Nokia', 3, 'nokia', NULL, NULL),
            (30, 'Sony', 3, 'sony', NULL, NULL),
            (31, 'Motorola', 3, 'motorola', NULL, NULL),
            (32, 'Data Entry & Back Office', 4, 'data-entry-back-office', NULL, NULL),
            (33, 'Sales & Marketing', 4, 'sales-marketing', NULL, NULL),
            (34, 'BPO & Telecaller', 4, 'bpo-telecaller', NULL, NULL),
            (35, 'Driver', 4, 'driver', NULL, NULL),
            (36, 'Office Assistant', 4, 'office-assistant', NULL, NULL),
            (37, 'Delivery & Collection', 4, 'delivery-collection', NULL, NULL),
            (38, 'Teacher', 4, 'teacher', NULL, NULL),
            (39, 'Cook', 4, 'cook', NULL, NULL),
            (40, 'Receptionist & Front Office', 4, 'receptionists-front-office', NULL, NULL),
            (41, 'Operator & Technician', 4, 'operator-technician', NULL, NULL),
            (42, 'IT Engineer & Developer', 4, 'it-engineers-developer', NULL, NULL),
            (43, 'Hotel & Travel Executive', 4, 'hotels-travel-executive', NULL, NULL),
            (44, 'Accountant', 4, 'accountant', NULL, NULL),
            (45, 'Designer', 4, 'designer', NULL, NULL),
            (46, 'Other Jobs', 4, 'other-jobs', NULL, NULL),
            (47, 'Motorcyles', 5, 'motorcyles', NULL, NULL),
            (48, 'Scooters', 5, 'scooters', NULL, NULL),
            (49, 'Sports Bike', 5, 'sports-bike', NULL, NULL),
            (50, 'Spare Parts', 5, 'spare-parts', NULL, NULL),
            (51, 'Bicycle', 5, 'bicycle', NULL, NULL),
            (52, 'TVs', 6, 'tvs', NULL, NULL),
            (53, 'Kitchen & Other Appliances', 6, 'kitchens-other-appliances', NULL, NULL),
            (54, 'Computers & Laptops', 6, 'computers-laptops', NULL, NULL),
            (55, 'Cameras & Lenses', 6, 'cameras-lenses', NULL, NULL),
            (56, 'Games & Entertainment', 6, 'games-entertainment', NULL, NULL),
            (57, 'Fridges', 6, 'fridges', NULL, NULL),
            (58, 'Computers Accessories', 6, 'computers-accessories', NULL, NULL),
            (59, 'Hard Disks', 6, 'hard-disks', NULL, NULL),
            (60, 'Printers', 6, 'printers', NULL, NULL),
            (61, 'Monitors', 6, 'monitors', NULL, NULL),
            (62, 'Acs', 6, 'acs', NULL, NULL),
            (63, 'Washing Machines', 6, 'washing-machines', NULL, NULL),
            (64, 'Commercial Vehicles', 7, 'commercial-vehicles', NULL, NULL),
            (65, 'Vehicle Spare Parts', 7, 'vehicles-parts', NULL, NULL),
            (66, 'Sofa & Dining', 8, 'sofa-dining', NULL, NULL),
            (67, 'Beds & Wardrobes', 8, 'beds-wardrobes', NULL, NULL),
            (68, 'Home Decor & Garden', 8, 'home-decors-garden', NULL, NULL),
            (69, 'Kids Furniture', 8, 'kids-furniture', NULL, NULL),
            (70, 'Other Households Items', 8, 'other-household-items', NULL, NULL),
            (71, 'Men Fashions', 9, 'men-fashions', NULL, NULL),
            (72, 'Women Fashions', 9, 'women-fashions', NULL, NULL),
            (73, 'Kids Fashions', 9, 'kids-fashions', NULL, NULL),
            (74, 'Action & Adventure Books', 10, 'actions-adventure-books', NULL, NULL),
            (75, 'Comic Books', 10, 'comic-books', NULL, NULL),
            (76, 'Horror Books', 10, 'horror-books', NULL, NULL),
            (77, 'Science Fiction', 10, 'science-fiction', NULL, NULL),
            (78, 'Fantasy Books', 10, 'fantasy-books', NULL, NULL),
            (79, 'Historical Fiction', 10, 'historical-fiction', NULL, NULL),
            (80, 'Short Stories', 10, 'short-stories', NULL, NULL),
            (81, 'Suspense & Thrillers', 10, 'suspense-thrillers', NULL, NULL),
            (82, 'Biographies & Autobiographies', 10, 'biographies-autobiographies', NULL, NULL),
            (83, 'Cookbooks', 10, 'cookbooks', NULL, NULL),
            (84, 'Gym & Fitness', 11, 'gym-fitness', NULL, NULL),
            (85, 'Musical Instruments', 11, 'musical-instruments', NULL, NULL),
            (86, 'Sports Equipments', 11, 'sports-equipments', NULL, NULL),
            (87, 'Other Hobbies', 11, 'other-hobbies', NULL, NULL),
            (88, 'Fishes & Aquarium', 12, 'fishes-aquarium', NULL, NULL),
            (89, 'Pet Food & Accessories', 12, 'pet-foods-accessories', NULL, NULL),
            (90, 'Dogs', 12, 'dogs', NULL, NULL),
            (91, 'Cats', 12, 'cats', NULL, NULL),
            (92, 'Other Pets', 12, 'other-pets', NULL, NULL),
            (93, 'Electronics & Computers', 13, 'electronics-computers', NULL, NULL),
            (94, 'Education & Classes', 13, 'education-classes', NULL, NULL),
            (95, 'Drivers & Taxi', 13, 'drivers-taxi', NULL, NULL),
            (96, 'Health & Beauty', 13, 'health-beauty', NULL, NULL),
            (97, 'Other Services', 13, 'other-services', NULL, NULL),
            (98, 'Brides', 14, 'brides', NULL, NULL),
            (99, 'Grooms', 14, 'grooms', NULL, NULL);"
        );
    }
}
