<?php return array(
    'meta_title' => 'Dealsy',
    'meta_description' => 'Dealsy',
    'og_url' => 'https://dealsy.in',
    'og_title' => 'Dealsy',
    'og_description' => 'Dealsy',
    'og_sitename' => 'dealsy',
    'fb_admins' => '502394297250285',
    'fb_app_id' => '1220934184931413',
    'og_type' => 'website',
    'og_publisher' => 'https://www.facebook.com/dealsy',
    'twitter_title' => 'Dealsy',
    'twitter_description' => 'Dealsy',
    'twitter_card' => 'summary',
    'twitter_site' => '@dealsy',
    'twitter_creator' => '@dealsy',
);
